sonar.projectKey=alekhyaakkiraju-droid_netflix-clone
sonar.organization=alekhyaakkiraju-droid

sonar.sources=src,server/src
sonar.tests=src,server/src
sonar.test.inclusions=**/*.test.js,**/*.test.ts,**/*.spec.js,**/*.spec.ts,tests/**/*
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,server/prisma/**,**/migrations/**,**/coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info,server/coverage/lcov.info
sonar.typescript.lcov.reportPaths=server/coverage/lcov.info

sonar.sourceEncoding=UTF-8
